# Data Cleaning Pipeline

This notebook covers the essential steps for cleaning and preparing data for analysis.

1) Import Libraries

In [4]:
import pandas as pd

2) Load Dataset

In [8]:
df = pd.read_csv("data/clean_data.csv")  
df.head()

,Student_ID,Age,Gender,Program,Semester,Exam_Score,Study_Hours_Per_Week,session_id,session_date,session_program,session_semester,status
0,1,22,Female,Computer Science,2,69.60,11.6,SES-2013,10/22/2023,Education,2,Present
1,49999,18,Male,Computer Science,7,70.81,10.8,SES-2002,11/2/2023,Computer Science,2,Present
2,49997,19,Male,Computer Science,7,70.81,10.8,SES-2046,2/11/2024,Computer Science,4,Present
3,49997,19,Male,Computer Science,7,70.81,10.8,SES-2045,7/4/2024,Education,8,Present
4,49997,19,Male,Education,4,53.99,11.5,SES-2001,2/5/2024,Computer Science,4,Present

3) Dataset Overview

In [9]:
print("Shape:", df.shape)
df.info()

Shape: (9995, 12)
<class 'pandas.DataFrame'>
RangeIndex: 9995 entries, 0 to 9994
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Student_ID            9995 non-null   int64
 1   Age                   9995 non-null   int64
 2   Gender                9995 non-null   str
 3   Program               9995 non-null   str
 4   Semester              9995 non-null   int64
 5   Exam_Score            9995 non-null   float64
 6   Study_Hours_Per_Week  9995 non-null   float64
 7   session_id            9995 non-null   str
 8   session_date          9995 non-null   str
 9   session_program       9995 non-null   str
 10  session_semester      9995 non-null   int64
 11  status                9995 non-null   str
dtypes: float64(2), int64(4), str(6)
memory usage: 1.4 MB

In [10]:
df.describe()

,Student_ID,Age,Semester,Exam_Score,Study_Hours_Per_Week,session_semester
count,9995.000000,9995.000000,9995.000000,9995.000000,9995.000000,9995.000000
mean,45756.091346,20.800200,4.223212,65.878524,8.925963,4.357479
std,2457.855491,2.143912,2.233539,11.925158,2.989134,2.157908
min,1.000000,17.000000,1.000000,26.020000,0.000000,1.000000
25%,43696.000000,19.000000,2.000000,57.560000,6.800000,2.000000
50%,45737.000000,21.000000,4.000000,65.890000,8.900000,4.000000
75%,47853.000000,22.000000,6.000000,74.410000,11.000000,6.000000
max,49999.000000,28.000000,8.000000,100.000000,18.200000,8.000000

4) Column Names

In [11]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Program', 'Semester', 'Exam_Score',
       'Study_Hours_Per_Week', 'session_id', 'session_date', 'session_program',
       'session_semester', 'status'],
      dtype='str')

5) Check Missing Values

In [12]:
missing_values = df.isnull().sum()
print(missing_values)

Student_ID              0
Age                     0
Gender                  0
Program                 0
Semester                0
Exam_Score              0
Study_Hours_Per_Week    0
session_id              0
session_date            0
session_program         0
session_semester        0
status                  0
dtype: int64

6) Handle Missing Values

In [13]:
df = df.dropna()

In [14]:
missing_values = df.isnull().sum()
print(missing_values)

Student_ID              0
Age                     0
Gender                  0
Program                 0
Semester                0
Exam_Score              0
Study_Hours_Per_Week    0
session_id              0
session_date            0
session_program         0
session_semester        0
status                  0
dtype: int64

7) Check for Duplicates

In [15]:
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

Duplicate rows: 0

8) Remove Duplicates

In [16]:
df = df.drop_duplicates()
duplicates = df.duplicated().sum()
print("Duplicate rows:", duplicates)

Duplicate rows: 0